server:
  port: 8081
spring:
  application:
    name: Vacancy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/seek_demo_vacancy?&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  flyway:
    validateMigrationNaming: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}